server {
  listen 80;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html;
  resolver 8.8.8.8 ipv6=off valid=30s;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /asset-proxy {
    if ($arg_url = "") { return 400; }
    proxy_pass $arg_url;
    proxy_ssl_server_name on;
    proxy_hide_header Content-Security-Policy;
    add_header Cache-Control "public, max-age=86400";
    add_header Access-Control-Allow-Origin "*";
  }

  location /openverse-api/ {
    proxy_pass https://api.openverse.org/;
    proxy_ssl_server_name on;
    add_header Access-Control-Allow-Origin "*";
  }

  location /microlink-api/ {
    proxy_pass https://api.microlink.io/;
    proxy_ssl_server_name on;
    add_header Access-Control-Allow-Origin "*";
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
    expires 7d;
    add_header Cache-Control "public, immutable";
  }
}
